### ISSUE TITLE
Upgrade to spring-boot 2.1.x with hibernate 5.3 and JPA 2.2

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#12]
Hibernate 5.3 is already out since a while and fully supports JPA 2.2:
https://www.thoughts-on-java.org/hibernate-5-3/
We should therefore use the official JPA 2.2 by replacing
```
      <dependency>
        <groupId>org.hibernate.javax.persistence</groupId>
        <artifactId>hibernate-jpa-2.1-api</artifactId>
        <version>1.0.0.Final</version>
      </dependency>
```
with
```
      <dependency>
        <groupId>javax.persistence</groupId>
        <artifactId>javax.persistence-api</artifactId>
        <version>2.2</version>
      </dependency>
```
To do so we also need to upgrade to hibernate 5.3 what will come with spring-boot 2.1.0:
https://github.com/spring-projects/spring-boot/issues/11725
But currently not even the milestone 2.1.0.M1 is in maven central.

**Comment by maybeec** [comment]
SpringBoot 2.1 is release since a while and it comes with Java 11 support.
Currently, Java 11 support is most valuable for projects as Java 8 is at EOL and Java 11 will be the next LTS to go for. Therefore, I think we should definitively do the migration soon.

**Comment by anmaso** [comment]
I also think we should go evergreen JVM and give support to older JVMs as exceptional cases.

**Comment by maybeec** [comment]
Nicely, SpringBoot 2.1 did not remove support for Java8, so we finally could and should have support for Java LTS versions.

**Comment by maybeec** [comment]
I just did it for my project, which seems to work smoothlessly.
Anyhow, we are in a early phase, so maybe some more bigger applications might face some issues. For my project I could not find any reason, why it should not work from the upgrade documentation.

https://github.com/spring-projects/spring-booT/wiki/Spring-Boot-2.1-Release-Notes#upgrading-from-spring-boot-20

So possibly low effort for devonfw.

**Comment by hohwille** [comment]
It would be lovely if we also add a migration step for devcon. Ideally from devon4j:3.0.0 to 3.0.1 (with only the version update) and from there to 3.1.0 containing all required changes we might see for this upgrade here.

**Comment by hohwille** [comment]
Done.

**Comment by hohwille** [comment]
I just tested these changes and found a severe issue:
```
Caused by: org.flywaydb.core.internal.license.FlywayEnterpriseUpgradeRequiredException: Flyway Enterprise Edition or Oracle upgrade required: Oracle 11.2 is past regular support by Oracle and no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition.
	at org.flywaydb.core.internal.database.base.Database.ensureDatabaseIsCompatibleWithFlywayEdition(Database.java:162)
```

This really sucks and feels like piracy. We need to consider how we want to proceed.

**Comment by maybeec** [comment]
I recognized this as well, anyhow for my project it was not an issue as we are running oracle 12.
Anyhow, flyway comes with a very small maintenance window for free. Everything else is paid.
I would suggest to not stop our migration plans as of that and better test compatibility the new spring boot and hibernate version, while downgrading flyway.
For the official release I would keep the spring boot managed version of flyway, but in the wiki, you can easily describe how to downgrade flyway to work with oracle 11 and what pitfalls may come with it.

**Comment by hohwille** [comment]
However, we might consider releasing a devon4j `3.0.1` release as well with the latest spring-boot `2.0.x` as they have fixed many CVEs by updating libs but not forcing to go to flyway.
Further we should maintain release-notes properly stating such facts as this is important to the projects.

**Comment by hohwille** [comment]
BTW: we have inconsistent statements regarding flyway 5.x.
In Yammer was stated that is neither works with Oracle 12.
Malte is however saying that it does work with Oracle 12, what would be much more relaxing as most projects are already on Oracle 12.

**Comment by hohwille** [comment]
We are talking about the latest flyway version 5.4.2 that comes with the new spring boot:
view-source:https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.4.RELEASE/spring-boot-dependencies-2.1.4.RELEASE.pom

For such flyway version the OSS edition has dropped support for Oracle 11 and 12.1.
However 12.2+ is still supported:
https://flywaydb.org/documentation/database/oracle

**Comment by hohwille** [comment]
spring-boot needs to be updated to `2.1.6.RELEASE` which is meanwhile the latest version available:
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.6.RELEASE/

Please create PR, then we merge and close this issue. Thanks.

**Comment by hohwille** [comment]
Finally at latest version with PR #111 threfore done.
