### ISSUE TITLE
Duplicate property in the pom of the server, already present in the parent pom

### ISSUE THREAD

**Issue by jconcavi** [devonfw/devon4j#133]
After create a project from scratch using the MAVEN archetype and changing the version of JAVA I got a message complaining that the project server has different target of the set.

I found this property in the server pom.xml 
>`<properties>
    <java.version>1.8</java.version>
  </properties>`

But is already defined in the parent pom.xml

> `<properties>
    <spring.boot.version>2.1.6.RELEASE</spring.boot.version>
    <devon4j.version>3.1.0</devon4j.version>
    <java.version>11</java.version>
    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.source>11</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <devonfw.test.excluded.groups>com.devonfw.module.test.common.api.category.CategorySystemTest</devonfw.test.excluded.groups>
  </properties>`

After having a look into the repository I found the duplicate property here:    [server pom](https://github.com/devonfw/devon4j/blob/develop/templates/server/src/main/resources/archetype-resources/server/pom.xml) 
please proceed to delete it and delegate in the parent pom the value of it

**Comment by hohwille** [comment]
@jconcavi thanks for the feedback.
Indeed a corrent obversation.
Trivial to fix: I created PR #143 as fix.

**Comment by hohwille** [comment]
Fixed with PR #143
