### ISSUE TITLE
Add fido2 support

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#139]
The standards fido2 and webauthn are the new hot topics revolutionizing authentication getting rid of passwords:
https://fidoalliance.org/fido2/

We should add a module/starter for devon4j supporting this OOTB.

**Comment by ssarmokadam** [comment]
Libraries which are currently available are:
https://github.com/webauthn4j/webauthn4j
https://github.com/webauthn4j/webauthn4j-spring-security

https://github.com/Yubico/java-webauthn-server

**Comment by hohwille** [comment]
@ssarmokadam thanks for sharing the links. Both projects look elaborate. However, the first one comes with spring-security integration out of the box and seems to be closely connected with it:
https://github.com/spring-projects/spring-security/issues/5238

As we build on top spring-security and webauthn4j meets our criteria (ASL 2.0 license https://github.com/webauthn4j/webauthn4j/blob/master/LICENSE.txt, active development, documentation https://webauthn4j.github.io/webauthn4j/en/, etc.) it seems a great choice. The only concern I can see is that it is driven more or less by one single active developer:
* https://github.com/webauthn4j/webauthn4j-spring-security/graphs/contributors
* https://github.com/webauthn4j/webauthn4j/graphs/contributors

However, I am also driver of such OSS projects so I do not see this as No-Go.

**Comment by ssarmokadam** [comment]
@hohwille Thanks for your reply. We do not have any release available for webauthn4j-spring-security yet. And as per comment by developer in issue spring-projects/spring-security#5238 . He is using this repo to test his new design. So should we use https://github.com/webauthn4j/webauthn4j dependency with reference to its webauthn4j-spring-security impl?

**Comment by maihacke** [comment]
...The only concern I can see is that it is driven more or less by one single active developer:
> 
> * https://github.com/webauthn4j/webauthn4j-spring-security/graphs/contributors
> * https://github.com/webauthn4j/webauthn4j/graphs/contributors
> 
> However, I am also driver of such OSS projects so I do not see this as No-Go.

When selecting technologies, we should pay attention to their future-proofness. A single developer is drawback in that sense. But there might be other indicators, like its "popularity", use by other frameworks etc.

**Comment by hohwille** [comment]
I would propose to close this issue:
Fido2 is a very cool feature and we could still link it from out documentation (access-control / authentication guide) to give hints towards this great technology option.
However, implementing this in devon4j does not really make sense to me.
This is a topic of IAM. Products like keycloak should support this.
If we try to implement this we might not be able to properly maintain this and we should instead focus on providing best-practices.
`devonfw` and `devon4j` focus on building (business) applications and those should not solve the authentication themselves but use JWT / OAuth and delegate it to an IAM product like keycloak.

**Comment by hohwille** [comment]
I added according hints to our authentication documentation and will now close this issue.
