### ISSUE TITLE
Should we add a microservices article in the documentation?

### ISSUE THREAD

**Issue by sjimenez77** [devonfw/devon4j#145]
In the **previous devonfw guide**, of which fortunately we have a backup, we had a microservice solution [based on the Netflix stack](https://github.com/devonfw-forge/devon-guide/wiki/devon-microservices).

Taking into account that probably is not the most interesting solution nowadays (docker, kubernetes, service meshes, etc.) it is still a valid one and maybe could be interesting to create a cookbook entry for those who ask about microservices in devonfw. 

Does it make sense? What do you think?

**Comment by hohwille** [comment]
I am happy to have room for any valueable hints within devonfw. The important aspects for me are:
* we should properly distinguish between what we suggest (1st class citizen) and what we offer als an alternative (while alternatives may be completely unmaintained whereas the official suggested way needs to get some kind of support).
* we should get a clear point of view where to put what. IMHO microservices are a quite cross-cutting toppic. General concepts, tools and patterns are not related to individual stacks of devonfw. So what should actually be part of `devon4j` and what is in the general part of `devonfw`?

**Comment by sjimenez77** [comment]
Totally agree. 

The thing is that, regarding this Netflix approach, **it is only valid in the context of Java applications**, so for that reason I thought that the devon4j documentation was the correct place to put it. The other point was that, as it is not a default solution but a valid one, mayba a entry in a **Cookbook section** could be fine. 

So, the question that now I have is: **Should we create a Cookbook section of cross-cutting topics in the guide or it will confuse again our users?** For example, we already have cookbook topics in devon4ng, so I am not sure if we create a global **Cookbook section** will be a good idea.

**Comment by hohwille** [comment]
Fine. You are right then devon4j documentation is the right place to keep this nugget of information. This will be addressed by this issue. Thanks for creating it and pointing this out.

I would love to have a cross-cuttion documentation space for devonfw. Currently we already have some but I do not entirely get where to put what. I can not say if should be a "Cookbook", etc. but what I can say is that we need to get startet with the obvious things:
* https://github.com/devonfw/devon4j/blob/develop/documentation/devonfw-code-contribution.asciidoc
* https://github.com/devonfw/devon4j/blob/develop/documentation/devonfw-documentation.asciidoc
* etc.

All these contents should IMHO not be specific for any stack. In `devon4j` they are even outdated and need rework. I am happy to assist but only if we agree on a new central space. This should be a reposiotry only for cross-cutting things with pure focus on documentation. But does that already exist? At least not with an obvious/intuitive/easy-to-find repository name:
* https://github.com/devonfw/devon - seems to be the old repo for the devonfw IP stuff
* https://github.com/devonfw/devonfw-tutorial-sources - might be the best match but the name is far from where a newbie would expect cross-cutting documentation for overall devonfw and the entire content seems to have a large historical backtrack making it not so easy to find things. AFAIK this is currently in progress to be improved.
* others I am missing?
* should we agree on a new simple repo name like `documentation`, `devonfw`, `cross-cutting`?
* should we do a clean start with a new empty repo and move the valuable reworked content step by step to this place (and avoid breaking something by renaming and cleaning up existing repos)? 
* I am not saying that we need more repos and more mess. I just want to say that it is sometimes easier to create something clean and new and then migrate stuff over and later delete the old repos after migration is complete.

**Comment by sjimenez77** [comment]
Maybe we could try to keep this as simplest as we can. 

Why do not use the existing [`general`](https://github.com/devonfw/devonfw-guide/tree/master/general) folder of the current devonfw-guide repository as it was intended to be the place for generic information? Inside you can already find the existing **Getting Started**, **Contributing Guide**, etc. Another approach can be simply to create a different folder `cross-cutting` folder and add these files. 

In any case we would only have to add the corresponding links to these new files inside the master documents in order to include them in the PDF and website accordingly.

**Comment by hohwille** [comment]
Done with PR #225 
Community is welcome to provide PRs for further improvements.
