### ISSUE TITLE
Cleanup archetype

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#171]
As a developer/architect, I want to create a new app without any strange code so that I only have to opt-in new features rather then removing things that nobody needs.

Suggestions:
* [x] remove the BinaryObject with all its related aspects
* [x] cleanup dummy users. Its fine to have something simple to work immediately as a jumpstart. But having `admin` or something would make more sense than still having the strange users inherited from the old `restaurant` demo app that has already been deleted long time ago and was replaced by MTS outside the stacks.
* [ ] improve the authentication machanism (e.g. via `AuthenticationManager`) such that permission expansion works everywhere including in JUnits and is designed for testability.
* [ ] consider creating a custom base class for `Authentication` with additional features such as efficient check of `hasAuthority(String)` (or `hasPermission(String)`) via an internal `Set<String>` and leaves room for custom properties associated with the user (JWT, Locale, personal data like email, etc.).

As the latter two points are not really "cleanup" we may better move them to separate issues. Just a marker for the moment so I do not forget this.

**Comment by vapadwal** [comment]
Above firet 2 point are fixed in PR https://github.com/devonfw/devon4j/pull/180

**Comment by vapadwal** [comment]
For the below 2 pending issue created another issue https://github.com/devonfw/devon4j/issues/224  as it was not having relation to it. Hence closing this issue

**Comment by vapadwal** [comment]
For the below 2 pending issue created another issue https://github.com/devonfw/devon4j/issues/224  as it was not having relation to it. Hence closing this issue
