### ISSUE TITLE
Create Changelog

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#181]
As discussed in PR #136, I want to have a CHANGELOG so that we document the changes done with a release and also give hints for migration.

See e.g.:
* https://github.com/devonfw/sonar-devon4j-plugin/blob/master/CHANGELOG.adoc
* See also valuable input from PR #136 
* State a general notice and link to devonfw-ide to tell about the migration/upgrade feature.

**Comment by hohwille** [comment]
See also https://github.com/devonfw/devon4j/releases vs. https://github.com/devonfw/sonar-devon4j-plugin/releases

**Comment by hohwille** [comment]
Mainly done. Things left for improvement:
* [ ] integrate the input from PR #136 
* [ ] create migration guide in `devonfw-ide` and change the link to that instead of to the `java` commandlet.

**Comment by hohwille** [comment]
PR #136 has been merged.
@vapadwal could you add the link to the new guide to the 3.0.0 version.
Could you also prepare the CHANGES for 2020.04.001?

**Comment by vapadwal** [comment]
> PR #136 has been merged.
> @vapadwal could you add the link to the new guide to the 3.0.0 version.
> Could you also prepare the CHANGES for 2020.04.001?

ok

**Comment by hohwille** [comment]
Closing as all is done now.
