### ISSUE TITLE
Deadlink to sample app in readme and sidebar

### ISSUE THREAD

**Issue by maihacke** [devonfw/devon4j#189]
Both files
- `documentation/_Sidebar.asciidoc`
- `README.adoc`

contain a reference to 
`tutorial-sample.asciidoc`
which does not exist.

**Comment by hohwille** [comment]
@maihacke thanks for the feedback. 👍 (BTW: You can directly edit the doc in the browser on github in the documentation folder via Pencil-icon and provide a PR with 2 clicks)
Done with PR #192.
