### ISSUE TITLE
ability to generate OpenApi files automatically from JAX-RS services

### ISSUE THREAD

**Issue by StevenGarcia-CG** [devonfw/devon4j#216]
As a developer I want to be able to have an automated swagger.json file generation, at present it's not possible with the JAX-RS implementation that devon4J offers

**Comment by StevenGarcia-CG** [comment]
There may be a solution to this, if we follow this cookbook done by @AbhayChandel :  https://github.com/devonfw-forge/devon-guide/wiki/Cookbook-Swagger

**Comment by hohwille** [comment]
Some time ago we had demand for generation of (swagger like) documentation for JAX-RS REST service interfaces. I spent two weekends and wrote this plugin:
https://github.com/mojohaus/servicedocgen-maven-plugin/
It should be relatively easy to extend this with the ability to already write the metamodel into a swagger.json file.
Of course the plugin should also be modified so it can not only be used for reporting (maven site generation) but also as regular plugin to generate standalone.
My problem is that I am very busy and continuously overloaded and do not expect to have time for this within the next couple of months. PRs are of course welcome, but in case I would have to do it, we need some special prioritization in devonfw...

**Comment by hohwille** [comment]
https://www.mojohaus.org/servicedocgen-maven-plugin/faq.html

> Can you also generate swagger.json?
>    No. Not yet. Please get involved and create a pull-request if you want to have this.

**Comment by hohwille** [comment]
https://github.com/mojohaus/servicedocgen-maven-plugin/issues/25

**Comment by hohwille** [comment]
moving to the next release as PR is still stuck.

**Comment by hohwille** [comment]
servicedocgen-maven-plugin has been updated accordingly.
However, shipping a release is failing:
https://groups.google.com/g/mojohaus-dev/c/CpjeLohpeAY

**Comment by hohwille** [comment]
Release performed and just staged. Should shortly appear here:
https://repo1.maven.org/maven2/org/codehaus/mojo/servicedocgen-maven-plugin/

**Comment by hohwille** [comment]
servicedocgen 1.0.0 is on its way:
https://groups.google.com/g/mojohaus-dev/c/Kchz1vUcqJA

I also did some advanced testing and found+fixed an important bug.
After update in devon4j to 1.0.0 we can close this issue and IMHO have a good solution.

**Comment by hohwille** [comment]
Release 1.0.0 is now available with bugfixes and swagger UI support:
https://repo1.maven.org/maven2/org/codehaus/mojo/servicedocgen-maven-plugin/1.0.0/
