### ISSUE TITLE
Use of Spring Interceptors

### ISSUE THREAD

**Issue by StevenGarcia-CG** [devonfw/devon4j#217]
As a developer I want to be able to use Spring Interceptors so I can handle endpoint interceptions without overwriting doFilter method.

Currently the /services/rest appended to al the URLs interferes with this

**Comment by hohwille** [comment]
I do not get your problem. Can you explain a little bit more?
Are you talking about AOP? What is the problem with your interceptor that you can not do currently?

**Comment by StevenGarcia-CG** [comment]
Hi @hohwille  thank you for your reply.

  Say I have an app already in production, and we detect the need to implement a Spring Interceptor (real use-case which we worked around with doFilter calls instead of using Interceptor)

  If I implement a Spring Interceptor, like in this guide: https://www.baeldung.com/spring-mvc-handlerinterceptor

  And I change my Controller to add `@RestController `and `@GetMapping` / `@PostMapping` to each endpoint instead of `@Path`/`@Get` annotations, I find that because of the addition of `/services/rest/` to every endpoint by default, I have no option left than to change all the endpoints, which for an app already in production would be a major upset

  The reason for this is that if I try to set my `@GetMapping` to values such as `"services/rest/myEndpoint"`, then the URL will end up like this: `server:port/myAppName/services/rest/services/rest/myEndpoint`.  And if I try to set the mapping as `("myEndpoint"),` the Interceptor doesn't recognize the URL, because it doesn't know where the `/services/rest` is coming from, and is expecting a URL such as: `server:port/myAppName/myEndpoint`

**Comment by maihacke** [comment]
I'm confused, where not using Spring MVC in Devon4j...

**Comment by hohwille** [comment]
Indeed this is a wrong expectation and the problem has nothing to do with devon4j.
You can use spring-mvc if you want (devon4j does strongly recommend to use JAX-RS but we do not force anybody). But if you want to apply AOP interceptors that are implemented only for spring-mvc and you are not using it you can not expect this to work. No issue of devonfw.
