### ISSUE TITLE
Improve the Authentication Mechanism

### ISSUE THREAD

**Issue by vapadwal** [devonfw/devon4j#224]
Improvement in Current Authentication Mechanism

* [ ] improve the authentication mechanism (e.g. via `AuthenticationManager`) such that permission expansion works everywhere including in JUnits and is designed for testability.
* [ ] consider creating a custom base class for `Authentication` with additional features such as efficient check of `hasAuthority(String)` (or `hasPermission(String)`) via an internal `Set<String>` and leaves room for custom properties associated with the user (JWT, Locale, personal data like email, etc.).

please see https://github.com/devonfw/devon4j/issues/171

**Comment by hohwille** [comment]
Will be fixed with PR #238

**Comment by hohwille** [comment]
Done with PR #238
