### ISSUE TITLE
License (ASL 2.0) declared wrong

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#25]
I got feedback from @MarcoRose that we have declared our license wrong. 
https://github.com/devonfw/devon4j/blob/develop/pom.xml#L603
Also the license URL (which was working before) is now broken:
https://github.com/devonfw/devon4j/blob/develop/pom.xml#L604
OMG what a stupid mess. We had that wrong for ~4 years and nobody has noticed or reported that earlier. Thanks to @MarcoRose to report this to me. I will fix it asap.

**Comment by soyrochus** [comment]
It should be

```
<licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
</licenses>
```

**Comment by hohwille** [comment]
PR #26 merged. Hence done.
