### ISSUE TITLE
Undocumented changes in devon4j JumpTheQueue

### ISSUE THREAD

**Issue by LuisChinchilla** [devonfw/devon4j#257]
As developers learning devon4j a group of workers detected since yesterday when you create a new project doesn't have the same structure described in the guide to create Jump The Queue app.

Apparently, now when you create new project ,some folder like type(where the different database folders are created) is missing and some sql archives too.

Although the user and password when initially launch the app is suppose to be 'waiter' but it doesn't work. We try with 'admin' and is working.
Maybe is more undocumented changes that we are not aware yet. 
It would be helpful if the documentation were updated for the people learning devonfw.

**Comment by dixyushi** [comment]
The guide document has been updated. The folder structure generation happens same way as described in document and the user and password is mentioned in document as 'admin'.
