### ISSUE TITLE
p12 files corrupted by maven resource filtering

### ISSUE THREAD

**Issue by maihacke** [devonfw/devon4j#266]
Our application template currently generates a maven config which enables resource filtering.
Sadly resource filtering corrupts binary files like p12-certificates.
If you use the new jwt module and put your certificate into src/main/resources/config you will receive an exception:

`java.io.IOException: DerInputStream.getLength(): lengthTag=111, too big.`

To avoid this resource filtering has to be disabled:

```
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <configuration>
          <nonFilteredFileExtensions>
            <nonFilteredFileExtension>p12</nonFilteredFileExtension>
          </nonFilteredFileExtensions>
        </configuration>
      </plugin>
...
```

Please not that this is a general problem with resourse filtering. Maven excludes only a few file types by default.
We could:
1. Document this behaviour and give an hint how to avoid in the jwt-module documentation
2. Add this to the application template, but this means again some clutter for people how do not use pkcs12 files
3. Do not enable resource filtering by default

**Comment by maihacke** [comment]
@ravicm2 fyi

**Comment by hohwille** [comment]
@maihacke thanks for reporting this problem.
Maybe we should just disable filtering by default.
We could also add a separate resource `src/main/filtered-resources` that are filter by default config if present. This makes it easier to avoid conflicts with binary files or other files that shall not be filtered for whatever reason.

**Comment by hohwille** [comment]
LOL
https://issues.apache.org/jira/browse/MNG-2478

**Comment by hohwille** [comment]
So simply disable filtering and we can close this issue.
Can you provide a PR?
