### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by charlieboygis** [devonfw/devon4j#27]
PDF link is broken on this setup wiki page:
https://github.com/devonfw/devon4j/wiki

**Comment by hohwille** [comment]
@charlieboygis thank you very much for this feedback. We need to fix that of course. As this is not the first time but I have seen this happening quite often, I proposed this alternative approach:
https://github.com/oasp/oasp-docgen/issues/18

**Comment by hohwille** [comment]
Fixed by updating link to 3.0.0-alpha.1 version that is now in maven central.
Once 3.0.0 is out, we can update the link again.
