### ISSUE TITLE
Kafka makes CI unstable

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#272]
### Expected behavior

As a developer of devon4j, I want to have reliable CI so that I can ensure quality of PRs.

### Actual behavior

Kafka module is making the CI completely unstable:
```
Shutdown broker because all log dirs in /tmp/kafka-6238832355242257459 have failed
```
In the end kafka seems to make surefire fail because of this. Maybe it even shuts down the JVM that was launched by surefire.
This blocks the CI and therefore all progress in `devon4j`.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. run travis CI

**Comment by maihacke** [comment]
We should update Spring Kafka 2.3.8, this should fix it (see https://github.com/spring-projects/spring-kafka/releases/tag/v2.3.8.RELEASE)

**Comment by maihacke** [comment]
Fixed with library upgrade.
