### ISSUE TITLE
Update Security-Guide to recent OWASP Top (2017)

### ISSUE THREAD

**Issue by jmsanmu** [devonfw/devon4j#277]
Hello, 
the links in the security section (https://github.com/devonfw/devon4j/wiki/guide-security) makes reference to the OWASP Top Ten points page. The OWASP portal seems to have changed, and now you can find the top ten points here: https://owasp.org/www-project-top-ten

That produces some 404 error behaviour on the devon4j Wiki, and some missalignment with the OWASP points.

Please could you fix it?

Thank you for your support and kind Regards,
José Manuel Sánchez

**Comment by hohwille** [comment]
Hi @jmsanmu and thanks for your feedback.
Actually it is not only about fixing some broken links. The security guide was still based on OWASP Top 10 2013 and current recent TOP 10 is 2017. We need to update. There have been 3 neu threads in the TOP 10.
I will take care of this and hope to find some time for it in the next weeks.
