### ISSUE TITLE
Travis broken: The job exceeded the maximum log length, and has been terminated.

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#286]
### Expected behavior

As a devon4j product owner, I want to have working and reliable CI so that I can monitor and garantee code health.

### Actual behavior

Travis-CI failes due to technical limitations:
```
The job exceeded the maximum log length, and has been terminated.
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. run travis on devon4j

### Related/Dependent Issues

PR #280 (where the error occurred the first time)

**Comment by hohwille** [comment]
What can we do?
* switch to travis enterprise
* run maven quitely
* suppress more log statements by raising thresholds (https://github.com/devonfw/devon4j/blob/develop/modules/test/src/main/resources/logback.xml#L16)

**Comment by maybeec** [comment]
Migrate to github actions?

**Comment by suvmanda** [comment]
The build failed due to .travis.yml file "dist: trusty". when use "dist: bionic" the build is successful.

**Comment by hohwille** [comment]
It was already indeterministic before and some builds succeeded while others failed.
If we are not experiencing the problem anymore with recent builds, it is fine to just close this issue.
I will observe some more builds before doing so.

**Comment by suvmanda** [comment]
This is under observation. In future if not comes the problem with the builds ,we will close the issue.

**Comment by hohwille** [comment]
problem did not occur anymore - hence closing.
