### ISSUE TITLE
Epic: cloud-native support

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#309]
Currently there are many trends towards cloud-native apps. The door opener for the Java ecosystem is [GraalVM](https://www.graalvm.org/) that allows to cross-compile Java apps to a native binary executable for a specific target CPU architecture and plattform. What sounds like removing the benefits from a cross-platform approach like Java actually allows Java to cope with demand of large IT landscapes with many apps (aka microservices) in a specific elastic (aka cloud) infrastructure: 
* having very fast startup times (JVM is quite slow here and therefore not ready for FaaS, etc.)
* reduced RAM utilization (JVM is not famous for being resource optimized, imagine that you can reduce your memory usage by 50% - quite a massive cost saving for RUN).

GraalVM is exactly addressing and solving these issues. However, to make your app work with GraalVM you have some limitations - the most imporatant one is avoid deep-reflection. Instead of generic reflection-based code, you will have compile-time introspection and generation so compilation may be a little slow but runtime will be faster.

As spring, spring-boot and spring-security are heavily based on deep-reflection, other frameworks like [Quarkus](https://quarkus.io/) or [Micronaut](https://micronaut.io/) showed up and are gaining a lot of attention.
On the other hand the spring-boot team is also following this trend and working on catching up to make [spring-boot work with GraalVM](https://blog.codecentric.de/en/2020/05/spring-boot-graalvm/).

We need to start supporting this demand for cloud-native apps in devon4j.
Therefore we need to sort out:
* what code patterns remain stable and what will change? AFAIK the impact is rather low. We just have to follow some of the `JEE -> JakartaEE -> microprofiles` movements. In case we would go to something else than spring-boot (quarkus) all the spring specific things would obviously change...
* what is the impact to our technology stack and archetype (app-template)? Shall and can we evolve it or should we rather put a new cloud-native alternative (e.g. based on quarkus) aside and see if it will become first-class citizen or not.
* what is the impact to our build-process and SCM? IMHO something rather easy to hide below the surface with maven, profiles, POM snipplets, etc.
* what is the impact to our tooling? IMHO also very low. I do see very little impact. Surely one might need GraalVM as compiler but IDEs and rest of the tooling will remain.

So the good message is already clear:

You can grasp the impact - the way you code use-cases, REST-Services, dependency-injection, etc. will not change. Most changes happen under the hood but will still very much affect the way you work.

**Comment by hohwille** [comment]
https://spring.io/blog/2021/03/11/announcing-spring-native-beta

**Comment by hohwille** [comment]
For quarkus see our roadmap: https://github.com/devonfw/devon4quarkus/issues/23
For spring-native it is currently open what we will do when.

**Comment by baumeister25** [comment]
@hohwille 
With whom can we dicuss if spring-native is still on the agenda? From my current understanding we're focussing on spring boot and quarkus.
At least in my opinion I would for now remove spring native from the roadmap and close this epic. We should revalidate that continuously.

**Comment by hohwille** [comment]
@baumeister25 I am fine with your suggestion.
However, spring-native still is build on spring-boot.
So all is just about adding some documentation and best-practices on spring-native in our spring section.
As we suggest quarkus for this as first-class-citizen, we should simply leave this up until a project shows up using devonfw and spring-native and wanting to contribute their insights and learning.
