### ISSUE TITLE
broken link for access-control-schema

### ISSUE THREAD

**Issue by maybeec** [devonfw/devon4j#318]
### Expected behavior

As a user, I want to read about access-control-schema so that I can implement an easy potentially temporary solution for my authorization.

### Actual behavior

Finding this spot https://devonfw.com/website/pages/docs/devon4j.asciidoc_guides.html#guide-access-control.asciidoc_access-control-schema-deprecated the link to the access-control-schema docs is broken.

**Comment by hohwille** [comment]
@maybeec thanks for the issue.
Like with #319 we have the same problem here: The website generation is broken and not devon4j. It works perfectly well and we are using proper AsciiDoc:
https://github.com/devonfw/devon4j/blob/develop/documentation/guide-access-control.asciidoc#access-control-schema-deprecated

**Comment by hohwille** [comment]
Sorry for rejecting too quickly last year in the hustle and thanks so much for fixing via PR.
As PR is merged, I am closing now.
