### ISSUE TITLE
devon4j application failed to start

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/devon4j#321]
### Expected behavior

As a user, I want to create devon4j application and start it.

### Actual behavior

I am able to create application but not able to start it. Below error occurs while starting application:

***************************
APPLICATION FAILED TO START
***************************

Description:

Field webSecurityConfigurer in com.cg.sample45.general.service.impl.config.BaseWebSecurityConfig required a bean of type 'com.devonfw.module.security.common.api.config.WebSecurityConfigurer' that could not be found.

The injection point has the following annotations:
	- @javax.inject.Inject()

Action:
Consider defining a bean of type 'com.devonfw.module.security.common.api.config.WebSecurityConfigurer' in your configuration.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  create devon4j project by using latest archetype available at https://oss.sonatype.org/content/repositories/comdevonfw-1380/
2. start application you should be able to see error.

**Comment by hohwille** [comment]
For the record: Always do commits linking the fixed issue in the comment as described here:
https://github.com/devonfw/.github/blob/master/CONTRIBUTING.asciidoc#committing-changes
Also link PRs with the fixing issues on github.

This way we do not miss out to assign issues to the right milestones and do not forget to close them.
