### ISSUE TITLE
Documentation outdated for JS tooling

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#344]
https://github.com/devonfw/devon4j/blob/master/documentation/guide-client-layer.asciidoc#javascript-for-java-developers

IMHO the above documentation needs a face-lifting. Tools like `gulp` are not required anymore, etc.
I think we can merge build and dependency management together.

**Comment by maybeec** [comment]
I even feel that we should remove it entirely. We already have mass of docs and the world has made some rounds. The need for Java developers to get in early touch with typescript or JavaScript is neither up to date anymore, nor a good way to start.

**Comment by hohwille** [comment]
> I even feel that we should remove it entirely.

Lets start this discussion in our community. Even though I agree I wont take this action if two experts say "this is common sense as of today" as I still think there are tons of Java developers who never put a foot into the JS/TS world. As soon as we have feedback from some more people in the community and no reasonable doubts, I am happy to drop this and reduce maintenance.

However, for our relase, I rather did a quick update than shipping obsolete nonsense or taking a decision to remove content that others may have bookmarked and later complain...
