### ISSUE TITLE
Archetype tutorial should show the latest devonfw version

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/devon4j#345]
As a developer, I want see the latest version of devonfw architetype in the tutorials so that I can copy and paste the code and run.

https://devonfw.com/website/pages/docs/devon4j.asciidoc_tutorials.html#tutorial-newapp.asciidoc_running-the-archetype

### Expected behavior
mvn -DarchetypeVersion=**2020-12-002** -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server archetype:generate -DgroupId=com.example.application -DartifactId=sampleapp -Dversion=1.0.0-SNAPSHOT -Dpackage=com.devonfw.application.sampleapp

### Actual behavior
mvn -DarchetypeVersion=3.1.0 -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server archetype:generate -DgroupId=com.example.application -DartifactId=sampleapp -Dversion=1.0.0-SNAPSHOT -Dpackage=com.devonfw.application.sampleapp

### Comments/Hints:

Use a variable for archetypeVersion and docgen should replace it with latest version

* OS: Windows/Linux/Mac?
* Browser: Chrome/Firefox/Safari?

**Comment by hohwille** [comment]
@sujith-mn thanks for noticing this problem and creating this issue 👍 
I will create a PR to fix it.
