### ISSUE TITLE
Change order of PerformanceLogFilter and DiagnosticContextFilter

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#38]
as stated in #36 the performance logging does not include the `correlationId`:
```json
{"timestamp":"2018-11-06T18:36:37.638+00:00","@version":"1","message":"http://localhost:8081/services/rest/security/v1/currentuser;6678;200;;","logger_name":"com.devonfw.module.logging.common.impl.PerformanceLogFilter","thread_name":"http-nio-8081-exec-6","level":"INFO","level_value":20000,"appname":"basic"}
```
This is due to the fact that the `DiagnosticContextFilter` is in the wrong filter order compared to the `PerformanceLogFilter` and hence removes the `correlationId` from the MDC before the performance data is logged.

Acceptance criteria:
correlationId is included in the performance logging.

**Comment by AbhayChandel** [comment]
Fixed as part of PR https://github.com/devonfw/devon4j/pull/50
