### ISSUE TITLE
Password encryption feature on devon CLI

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/devon4j#384]
As a developer, I want password encryption feature so that I can add my encrypted password (eg: database password) in application.properties 

eg:
```
devon jasypt encrypt masterPassword=secret input=passwordToBeencrypted
```

Refer the below documentation:
https://github.com/devonfw/devon4j/blob/master/documentation/guide-configuration.asciidoc#security

**Comment by hohwille** [comment]
wrong repo. Can you move to `ide` repository?

**Comment by sujith-mn** [comment]
moved to ide:
https://github.com/devonfw/ide/issues/575
