### ISSUE TITLE
Access-control should honor roles by default

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#385]
devon4j ships with an application template that already comes with a login mechanism and a ready to use function based access control for authorization.
However, there are two places that do not seem to fit together:
1. https://github.com/devonfw/devon4j/blob/92a6ec127b90542550c2ecd6f2615ee28200bb2e/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/service/impl/config/BaseWebSecurityConfig.java#L115
2. https://github.com/devonfw/devon4j/blob/92a6ec127b90542550c2ecd6f2615ee28200bb2e/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/security/BaseUserDetailsService.java#L86

So with 1. we also assign a role to a user.
However, with 2. we ignore this role assignment and simply take the login username as role what is obviously nuts (we already have a todo comment on top of this).
Aint there a servlet JEE api to get the roles of the user that we could use here? I assume the roles assigned via spring-security fluent API can also be retrieved somehow.

**Comment by tobka777** [comment]
I have looked at it. Wouldn't you just have to replace this line 
https://github.com/devonfw/devon4j/blob/92a6ec127b90542550c2ecd6f2615ee28200bb2e/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/security/BaseUserDetailsService.java#L48
with
`User userData = new User(user.getUsername(), user.getPassword(), user.getAuthorities());`

`user.getAuthorities()` returns for user admin [ROLE_Admin]. 
And we don't need the methods getAuthorities and getRoles.

Maybe I am also wrong.

**Comment by hohwille** [comment]
Sounds good 👍 
Sometimes the solutions are easy ;)

**Comment by hohwille** [comment]
One concern:
The `ROLE_` prefix is undesired. We already introduced some solution for spring-security to avoid adding this by default.
So we should also strip it off here if present.

**Comment by hohwille** [comment]
https://github.com/devonfw/devon4j/blob/682c72e6440c9172806ae6393c553b2dc1853459/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/logic/impl/config/DefaultRolesPrefixPostProcessor.java#L16

https://github.com/devonfw/devon4j/blob/682c72e6440c9172806ae6393c553b2dc1853459/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/service/impl/config/WebSecurityBeansConfig.java#L39

**Comment by sujithmn** [comment]
Another way to strip "ROLE_"
https://stackoverflow.com/questions/38134121/how-do-i-remove-the-role-prefix-from-spring-security-with-javaconfig

**Comment by hohwille** [comment]
I would suggest to change this:
https://github.com/devonfw/devon4j/blob/92a6ec127b90542550c2ecd6f2615ee28200bb2e/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/security/BaseUserDetailsService.java#L63

to:
```
protected Set<GrantedAuthority> getAuthorities(User user) throws AuthenticationException {
 
  Objects.requireNonNull(username, "username");
  // determine granted authorities for spring-security...
  Set<GrantedAuthority> authorities = new HashSet<>();
  Collection<String> accessControlIds = getRoles(user);
  Set<AccessControl> accessControlSet = new HashSet<>();
  for (String id : accessControlIds) {
    boolean success = this.accessControlProvider.collectAccessControls(id, accessControlSet);
    if (!success) {
      LOG.warn("Undefined access control {}.", id);
    }
  }
  for (AccessControl accessControl : accessControlSet) {
    authorities.add(new AccessControlGrantedAuthority(accessControl));
  }
  return authorities;
}
```

And then:
https://github.com/devonfw/devon4j/blob/92a6ec127b90542550c2ecd6f2615ee28200bb2e/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/security/BaseUserDetailsService.java#L82
to:
```
  private Collection<String> getRoles(User user) {
    Set<String> roles = new HashSet<>();
    for (GrantedAuthority authority : user.getAuthorities()) {
      String authorityId = authority.getAuthority();
      if (authorityId.startsWith("ROLE_")) {
        authorityId = authorityId.substring(5);
      }
      roles.add(authorityId);
    }
    return roles;
  }
```

(code written in Browser, not tested so just an initial guess)

Also I found this hack that needs to be removed:
https://github.com/devonfw/devon4j/blob/92a6ec127b90542550c2ecd6f2615ee28200bb2e/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/security/BaseUserDetailsService.java#L51

**Comment by hohwille** [comment]
Then we can move this line:
https://github.com/devonfw/devon4j/blob/92a6ec127b90542550c2ecd6f2615ee28200bb2e/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/security/BaseUserDetailsService.java#L44

before this one:
https://github.com/devonfw/devon4j/blob/92a6ec127b90542550c2ecd6f2615ee28200bb2e/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/security/BaseUserDetailsService.java#L48

And provide `user` as arg instead.

**Comment by hohwille** [comment]
> Another way to strip "ROLE_"
> https://stackoverflow.com/questions/38134121/how-do-i-remove-the-role-prefix-from-spring-security-with-javaconfig

Will we get another PR for this? Once we have a PR or issue for this great improvement, we can close this issue.
