### ISSUE TITLE
Better example for package structure

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/devon4j#388]
As someone who is new to devon4j, I want to have a clear and correct example for the package structure so that I can understand the concepts.

The example on https://devonfw.com/website/pages/docs/devon4j.asciidoc_coding-conventions.html#coding-conventions.asciidoc_packages should be better and the description in the table should be correct.

The "devonfw" in the example makes it hard to understand that it has to be adapted because the reader wants to use devonfw and the "application" makes it had to map the example to the structure above.
A better example could be something like "com.mycustomer.myapplication.ordermanagement.dataaccess.api.repo"

The table could have the following examples:
«rootpackage»: com.mycustomer
«application»: myapplication
«component»: ordermanagement
«layer»: dataaccess
«scope»: api
«detail»: repo

It would be best to have the same example on https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc_create, too. There should also be a linkt to the page page with the conventions.

**Comment by denise-khuu** [comment]
Maybe also add:
«rootpackage»: com.example
«application»: application.sampleapp
here:
https://github.com/devonfw/devon4j/blob/master/documentation/tutorial-newapp.asciidoc
or link it to the naming convention.

**Comment by baumeister25** [comment]
Did the bugfix fixed the issue? Is there anything left here?

**Comment by hohwille** [comment]
As always the links pointing to our website are all meanwhile broken (404).
Only github links remain more or less stable. So the actual documentation referenced is this one:
https://github.com/devonfw/devon4j/blob/master/documentation/coding-conventions.asciidoc#packages

I do not see how https://github.com/devonfw-tutorials/tutorial-compiler/pull/231/files really fixes or relates to this issue.

So I just did the change myself - was most probably easier than writing the issue itself ;)
https://github.com/devonfw/devon4j/commit/40a7a96aa33ae4477e0bc9523d79d7d315cd3494

**Comment by hohwille** [comment]
For the sake of completeness and perfection, I also addressed the implied optional wish ("It would be best to have ..."):
https://github.com/devonfw/ide/commit/4126699dd3b0e1d1a23d16e2352716d266c45c07
