### ISSUE TITLE
Ability to log custom fields via SLF4J

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#39]
As discussed in #36:
It would be awesome to find a way that via SLF4J we could log custom fields such as status-code or respons-time for the performance logging  would end up as separate fields in the JSON. This would be very powerful  for kibana dashboards, etc. At the moment we are producing CSV in the  message was is not so great. I will file an issue for this but we will  not be able to address this before the release.
Current result:
```json
{"timestamp":"2018-11-06T18:36:37.638+00:00","@version":"1","message":"http://localhost:8081/services/rest/security/v1/currentuser;6678;200;;","logger_name":"com.devonfw.module.logging.common.impl.PerformanceLogFilter","thread_name":"http-nio-8081-exec-6","level":"INFO","level_value":20000,"appname":"basic"}
```
Expected result:
```json
{"timestamp":"2018-11-06T18:36:37.638+00:00","@version":"1","message":"http://localhost:8081/services/rest/security/v1/currentuser","response-time":"6678","status-code":"200","logger_name":"com.devonfw.module.logging.common.impl.PerformanceLogFilter","thread_name":"http-nio-8081-exec-6","level":"INFO","level_value":20000,"appname":"basic"}
```

**Comment by hohwille** [comment]
Of course it would be possible to add the values temporary via MDC but IMHO this would be hackish and only suitable if there is no other way.

**Comment by maihacke** [comment]
The PR shows how to that. It's quite easy. Is there a need for separate documentation? We could write some words in the logging-guide....

**Comment by hohwille** [comment]
Fixed with PR #209 hence closing.

**Comment by hohwille** [comment]
logging guide would be the prefect place. Does not make sense to create another guide for this.

**Comment by maihacke** [comment]
> logging guide would be the prefect place. Does not make sense to create another guide for this.

Created another https://github.com/devonfw/devon4j/pull/213 for that
