### ISSUE TITLE
Remove the ROLE_ prefix from Spring Security using JavaConfig

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/devon4j#400]
As a Developer, I want to remove ROLE_ using java config.

Refer: https://stackoverflow.com/questions/38134121/how-do-i-remove-the-role-prefix-from-spring-security-with-javaconfig

Related Issue: https://github.com/devonfw/devon4j/issues/385

Acceptance-Criteria:
* [ ] class deleted https://github.com/devonfw/devon4j/blob/682c72e6440c9172806ae6393c553b2dc1853459/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/logic/impl/config/DefaultRolesPrefixPostProcessor.java#L16
* [ ] bean removed https://github.com/devonfw/devon4j/blob/682c72e6440c9172806ae6393c553b2dc1853459/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/service/impl/config/WebSecurityBeansConfig.java#L39
* [ ] `@RolesAllowed` annotation still working and spring-security is matching AccessControls from the permission annotated via `@RolesAllowed` without any artificial `ROLE_` prefix.

**Comment by tobka777** [comment]
Unfortunately, I had no success with the bean from the instructions. I tried a few approaches and none worked. That's when I saw roles being used with `inMemoryAuthentication`. Instead I used authorities and the prefix `ROLE_` was not there anymore.

**Comment by hohwille** [comment]
> Unfortunately, I had no success with the bean from the instructions. I tried a few approaches and none worked. That's when I saw roles being used with `inMemoryAuthentication`. Instead I used authorities and the prefix `ROLE_` was not there anymore.

I assume there is a missunderstanding here.
There are two independent places where a `ROLE_` prefix is added:
1. when using the `roles(String)` method of `inMemoryAuthentication` in WebSecurityConfig.
2. implicitly by spring-security when GrantedAuthorities are matched with the roles configured via `@RolesAllowed` annotation.

I assume @tobka777 is talking about 1. while @sujith-mn created this issue for 2.
We should still try to create a PR for 2. as suggested by @sujith-mn to simplify our spring usage.

**Comment by hohwille** [comment]
Was autoclosed by PR #402. Reopening as still not implemented as described.
