### ISSUE TITLE
create release 3.0.0

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#43]
create the release:
* [x] bump version, tag, build, deploy to OSSRH, verify, close release
* [x] release/stage to maven central.
* [x] check for #42 and once done review and merge the community wiki
* [x] bump doc version deploy doc release to OSSRH and maven central

**Comment by hohwille** [comment]
https://oss.sonatype.org/content/repositories/comdevonfw-1035/
@vapadwal could you use this for MTSJ and verify all is sane?

**Comment by vapadwal** [comment]
I have tested in different network and it work. So now mtsj is working with above

**Comment by hohwille** [comment]
@AbhayChandel thanks for deploying the documentation as well.
It is now in central:
http://repo1.maven.org/maven2/com/devonfw/java/doc/devon4j-doc/3.0.0/devon4j-doc-3.0.0.pdf
So all is complete now.
