### ISSUE TITLE
devon4j migration issues

### ISSUE THREAD

**Issue by sujithmn** [devonfw/devon4j#437]
devon java migrate does the migration job well. But found below 2 issues.
1. Compilation error from DbTestHelper.

	  the issues are due to the below lines of code:

```
	  private MigrationVersion migrationVersion;
	  ....
	  
	  if (this.migrationVersion != null) {
	    this.flyway.setTarget(this.migrationVersion);
	  }
	  
	  …..
	  
	  public void setMigrationVersion(String migrationVersion) {
	    this.migrationVersion = MigrationVersion.fromVersion(migrationVersion);
	  }
```

2. Nullpointer exception from repository.findByCriteria 

	` 	addOrderBy(query, alias, criteria.getPageable().getSort());`

Change the code as below fixes the issue

```
    if (criteria.getPageable() == null) {
      criteria.setPageable(PageRequest.of(0, Integer.MAX_VALUE));
    } else {
      addOrderBy(query, alias, criteria.getPageable().getSort());
    }
```

**Comment by ssarmokadam** [comment]
It is done by @sujith-mn and PR is merged.
