### ISSUE TITLE
devon4j-logging depends on httpclient

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#438]
I just accidentally stumbled over the fact that `devon4j-logging` depends on `httpclient`:
https://github.com/devonfw/devon4j/blob/master/modules/logging/pom.xml#L51

IMHO this is a bug and that exists from day 1 of devon4j.
However, it did not exist in oasp4j-logging:
https://github.com/oasp/oasp4j/blob/develop/modules/logging/pom.xml

So IMHO an unintendet bug that happened when oasp4j was "copied" to create devon4j.
This dependency should simply be removed as it is missplaced.

**Comment by ssarmokadam** [comment]
@hohwille Ayushi removed this dependency and raised PR https://github.com/devonfw/devon4j/pull/440 but build is failing. We are using this in PerformanceLogger class. In oasp4j also we have this dependency at https://github.com/oasp/oasp4j/blob/4ff7e9eb9900455befc40e1375efb64005205de9/modules/logging/pom.xml#L47

**Comment by hohwille** [comment]
Remove the dependency to `HttpStatus`:
* https://github.com/devonfw/devon4j/blob/master/modules/logging/src/main/java/com/devonfw/module/logging/common/impl/PerformanceLogFilter.java#L17
* https://github.com/devonfw/devon4j/blob/master/modules/logging/src/main/java/com/devonfw/module/logging/common/impl/PerformanceLogFilter.java#L72
* https://github.com/devonfw/devon4j/blob/master/modules/logging/src/main/java/com/devonfw/module/logging/common/impl/PerformanceLogFilter.java#L90

For the last one simply hardcode `500`.

**Comment by hohwille** [comment]
PR #440 has been merged almost a year ago. Hence closing this issue.
