### ISSUE TITLE
CSRF support in Quarkus

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/devon4j#448]
Current documentation can be found at https://devonfw.com/website/pages/docs/devon4j.wiki_devon4j.asciidoc_guides.html#guide-csrf.asciidoc 
Move CSRF concept/overview part in General section. Add CSRF in devon4j and CSRF support in Quarkus.
reference: https://github.com/quarkusio/quarkus/issues/8399

**Comment by baumeister25** [comment]
Hi @ssarmokadam ,

additionally to the docu I see the following module in deovn4j for CSRF.
In my eyes the module does not provide much benefit. I think it could be removed in favour of a guide step by step guide for quarkus and spring.

https://github.com/devonfw/devon4j/tree/master/modules/security-csrf

**Comment by ssarmokadam** [comment]
I am able to get csrftoken with undertow library. But login for user is missing in sample app. Currently I am implementing login functionality
