### ISSUE TITLE
Refactor cors guide

### ISSUE THREAD

**Issue by lilliCao** [devonfw/devon4j#468]
Currently, we have 2 cors guide [here ](https://github.com/devonfw/devon4j/blob/master/documentation/guide-cors-support.asciidoc)and [here](https://github.com/devonfw/devon4j/blob/master/documentation/quarkus/guide-cors-support.asciidoc), which have some duplicates. Please refactor to have a general guide and spring-/quarkus-specific stuff in the subfolder.

**Comment by GuentherJulian** [comment]
Closed with https://github.com/devonfw/devon4j/pull/471
