### ISSUE TITLE
RevisionMetadata 

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#47]
RevisionMetadata (https://github.com/devonfw/devon4j/blob/c8f25cb073909db78d0329eda7ce44d93c9e9bae/modules/jpa-basic/src/main/java/com/devonfw/module/jpa/dataaccess/api/RevisionMetadata.java) is located in `dataaccess` layer.
However, this is the API that is also suitable to be exposed to logic layer and even via service APIs.
Therefore this interface and most probably its type implementation (https://github.com/devonfw/devon4j/blob/9b8f9461997bb5d8048a9fec42bec3625652eec3/modules/jpa-basic/src/main/java/com/devonfw/module/jpa/dataaccess/api/RevisionMetadataType.java) would need to be moved to `common` instead.

In order not to break compatibility, we would create a deprecated interface in the old place extending from the moved interface (and same for the type). The lazy implementation would still also implement the deprecated interface.
Then projects have the chance to migrate their code (what should also be supported by devcon migration).
In a later release we can then remove the deprecated code.

**Comment by hohwille** [comment]
See current workarounds:
* https://github.com/devonfw/sonar-devon-plugin/blob/988ef16e32cc3833ee2cb773f9394edae927b302/src/main/java/com/devonfw/ide/sonarqube/common/impl/check/DevonArchitectureLayerService2DataaccessCheck.java
* https://github.com/devonfw/sonar-devon-plugin/blob/e1a825562684164cca803398fe3e3f1f28cf1bfb/src/main/java/com/devonfw/ide/sonarqube/common/impl/check/DevonArchitectureLayerLogic2Dataaccess4ComponentCheck.java

**Comment by Rohit90700** [comment]
Hi @hohwille , I have create PR for this issue - https://github.com/devonfw/devon4j/pull/134 .
Note :- There is a entity AdvancedRevisionEntity.java and AdvancedRevisionListener.java copied to common because RevisionMetadataType.java having its reference.

**Comment by hohwille** [comment]
Done with PR #137.
Cleanup with #138 for next release.
