### ISSUE TITLE
Describe the usage of Querydsl integration in more detail

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw/devon4j#482]
The devon4j [query guide](https://github.com/devonfw/devon4j/blob/master/documentation/guide-jpa-query.asciidoc#dynamic-queries) recommend to use Querydsl to build dynamic queries. In the general guide we describe how to use Querydsl using auto generated meta classes as this can be used in Spring and Quarkus applications. As mentioned [here](https://github.com/devonfw-forge/devonfw-microservices/issues/24), we should describe also how to integrate Querydsl and the Querdsl annotation processor and maybe also how to build expressions in more detail.

**Comment by maybeec** [comment]
outcome should be a devonfw-tutorials/tutorials
