### ISSUE TITLE
Guide the user for a decision between Spring and Quarkus

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw/devon4j#489]
As an inexperienced user starting with devon4j, I would like some advice on whether to start with Spring or Quarkus and what is the preferred framework for which problem.
When opening the [Java section](https://devonfw.com/website/pages/docs/devon4j.asciidoc.html) on the website, the user sees that devon4j is divided into Spring and Quarkus. Under the subheadings he can find some advantages and disadvantages of the frameworks. But he has no hints or advice which framework is the right one for his purposes. So he does not know how to start and where to start.

**Comment by hohwille** [comment]
As always the link to the website is meanwhile broken.
On github the link is stable and would be:
https://github.com/devonfw/devon4j/blob/master/documentation/devon4j.asciidoc

Here you can see that the documentation already guides the user exactly in this way.

> With devon4j we support both [spring](https://github.com/devonfw/devon4j/blob/master/documentation/spring.asciidoc) and [quarkus](https://github.com/devonfw/devon4j/blob/master/documentation/quarkus.asciidoc) as major frameworks. However, the general coding patterns are based on common Java standards mainly from [Jakarta EE](https://jakarta.ee/) and therefore do not differ between those frameworks. Therefore, the [general](https://github.com/devonfw/devon4j/blob/master/documentation/devon4j.asciidoc#general) section contains all the documentation that is universal to Java and does not differ between the two frameworks. Only the sections [spring](https://github.com/devonfw/devon4j/blob/master/documentation/spring.asciidoc) and [quarkus](https://github.com/devonfw/devon4j/blob/master/documentation/quarkus.asciidoc) contain documentation that is specific to the respective approach.

> If you’re trying to decide which of the two frameworks to use, have a look at [this guide](https://github.com/devonfw/devon4j/blob/master/documentation/decision-between-Spring-and-Quarkus.asciidoc).

The only problem left I can find is that the decision guide linked at the end is not included in the main asciidoc file and therefore the link is broken in the PDF (and most probably on the website).
