### ISSUE TITLE
Naming conventions Quarkus: rename `service` package

### ISSUE THREAD

**Issue by yntelectual** [devonfw/devon4j#491]
In the [modern package structure](https://devonfw.com/website/pages/docs/guide-structure-modern.asciidoc.html) the package/layer containing boundary API related classes is called `service`, which is a very ambiguous term.    
I would like to suggest renaming of this into something more descriptive: `rest`, `rs`, `api`.

**Comment by rafaelvicariabarker** [comment]
https://github.com/devonfw-sample/devon4quarkus-reference/pull/35
https://github.com/devonfw-sample/devon4quarkus-order/pull/7
https://github.com/devonfw/devon4j/pull/505

**Comment by rafaelvicariabarker** [comment]
All pull requests have been merged
