### ISSUE TITLE
Quarkus quide for API first development

### ISSUE THREAD

**Issue by yntelectual** [devonfw/devon4j#493]
A common use case in microservice projects is to quickly provide a service, that provides some predefined API, or that a solution designers define the API first, and then the code that provides it is implemented.  
To support this, we should provide a guide in Devon/Quarkus docs, that describes an approach for this:

* overview of API first
* tools that allow generation of REST API classes from Openapi schemas
* integration with Microprofile Rest, configuration options...
* integration as maven plugin

As base we could use the existing guide in 1000kit guides - https://1000kit.gitlab.io/guides/docs/quarkus/quarkus-apifirst-project/ and check the state of the 2 most used openapi codegens (https://github.com/OpenAPITools/openapi-generator and https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen-maven-plugin)

**Comment by maybeec** [comment]
outcome should be a devonfw-tutorials/tutorials
