### ISSUE TITLE
Reference project - streamline helm resources + docu

### ISSUE THREAD

**Issue by yntelectual** [devonfw/devon4j#494]
The reference project currently contains `helm`, `helm-otel` and `k8s` resources. The `k8s` and `helm` should be cleaned up (they still contain 1000kit references from the CapUniversity course) and the `k8s` deployment guide contains specific instructions for k3d - which probably should be more generic.   The k8s `deployment.yaml` contains a hardcoded ref to `default` namespace, which should be there(https://github.com/devonfw-sample/devon4quarkus-reference/blob/master/k8s/deployment.yaml#L10).
The `helm-otel` is not mentioned in the docu at all, not sure what it is for.

**Comment by GuentherJulian** [comment]
@yntelectual we did some refactoring on the helm/k8s resources and added some documentation with https://github.com/devonfw-sample/devon4quarkus-reference/pull/32. Do you agree with the changes. It there anything left to do for this issue?

**Comment by hohwille** [comment]
The linked PR was already merged. Issues about sample apps should be raised in the repo of that sample app itself. Hence closing this issue.
