### ISSUE TITLE
Reference project cleanup - remove `general` package, abstract classes etc

### ISSUE THREAD

**Issue by yntelectual** [devonfw/devon4j#495]
The reference project contains `general` top level package, that contains some code that should not be in a reference project - either it should come from 1000kit-quarkus libs, or some existing devon lib if exists.  There is a PR open that removes most of it - but AbstractEntity still stays.
![image](https://user-images.githubusercontent.com/1354787/139810264-9abcf547-614b-4dcd-977e-e1c9855ac937.png)
Additionally we still have `UC` classes and their impl classes which look totally out of place in a lean, cloud native project .   
The usage of Spring data, and Query DSL should also be documented - if that is the Devon recommended approach.

**Comment by GuentherJulian** [comment]
@hohwille what do you think is the best solution for the code we have in the `general` package right now (like `ApplicationPersistenceEntity`) and used across multiple projects. Since we removed the tkit libraries from the reference project, I think it would be best to have a devonfw specific solution.

**Comment by hohwille** [comment]
We have contradicting requirements here.
However, most of our users want to have exactly the opposite:
They do _not_ want a devonfw as framework that makes them dependent on external code that they can not easily adopt and control. Therefore we went for the approach to put some common code in this general package.
The idea is that CobiGen can generate all the required code into your project automatically if you want to add a specific feature. However, you always have the freedom to change and adapt that code to your own requirements (may it be adding some extra logging, changing the mapping of your primary-keys, etc.
We had serious complaints from users when we had put things like `ApplicationPersistenceEntity` into a "locked" library from devonfw.
I therefore tend to close this issue as rejected. However, I leave it open for a while for further discussion in case there is more feedback or disagreement on my point of view.
