### ISSUE TITLE
Improve the structure of the Java General section on the homepage

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw/devon4j#511]
There are currently many guides in the 'General' section of Java in the [homepage outline](https://devonfw.com/website/pages/docs/devon4j.asciidoc_general.html). Therefore this outline becomes quite long and unclear when expanding this section.

![homepage_general](https://user-images.githubusercontent.com/69513769/145780866-204d2efe-ccc1-4ba6-9dc0-0b412e755e92.PNG)

We should think about a solution to improve the structure of the outline so that it is easier for the reader to read and find the right documents.

**Comment by hohwille** [comment]
@GuentherJulian thanks for this issue. I fully agree that it is kind of confusing for the reader.
However, IMHO the answer is _not_ to restructure some asciidoc files but to generally stop making the website a hierarchical bullet list of our includes of asciidoc files. It is perfectly fine to have small asciidoc files per specific topic and to have many of them. It is rather a question how to present them to the end user.
Options could be:
* rely mainly on searches
* try to find a priority of topics (by asking users, checking google analytics, etc.) and move less important topics deeper in the hierarchy, ...
* create custom landing pages dedicated per personas that lead to the specific pages relevant for that context 
* or even create multi-dimensional entry paths that directly guide to the topics of interest (e.g. first choose your stack like `Java`, `.NET`, `TypeScript`, etc. then e.g. in `TypeScipt` choose frontend or backend, in `TypeScript/Frontend` choose `Angular` or `React`, etc.

The bullet points are sorted with most maintenance effort downwards.

**Comment by hohwille** [comment]
Meanwhile the website team also agreed about this strategy so I am closing this here.
Changes need to be done in the website build itself.
