### ISSUE TITLE
Changelog for Quarkus

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw/devon4j#513]
Create a changelog documenting everything that has been done regarding Quarkus in devon4j so far

**Comment by mustafaokyay** [comment]
- Remove @APIResponse annotations and added ServicedocGen plugin to support OpenAPI generation in Reference Project
- Guide: Quarkus vs. Spring Native
- Guide: Decision between Spring and Quarkus

**Comment by EduardKrieger** [comment]
- Added support for Quarkus creation to devon java create 
- Guide: Quarkus Quickstart

**Comment by GuentherJulian** [comment]
# Quarkus changelog

## Documentation
* Separated the Java section of the homepage into 'General', 'Spring' and 'Quarkus'
* Guiding the reader
    - Pros and cons of Quarkus
    - Guide to the Reader
    - Guiding for a decision between Spring and Quarkus
* Getting started with Quarkus
    * Quick start guide: Introduction to Quarkus and it's functionality, create and run first Quarkus application
    * Creating of native images
    * Getting started with Quarkus for Spring developers
    * Migration from Spring to Quarkus (incl. performance comparision)
    * Comparision between Spring Native and Quarkus
    * Template guide providing links to the Quarkus code generator with preselected tools/extensions
* Project structure: Invented 'new' modern project structure for Quarkus applications, renamed Data-Access layer to domain layer
* Logic layer: Suggestion to implement logic layer using Use-Case approach rather than component facade
* Technical guides
    * OpenAPI guide: showing usage of Quarkus Smallrye extension and ServicdocGen maven plugin, incl. Katacoda Tutorial
    * API first guide: showing the usage of OpenAPI generator plugin
    * JPA and query guide: showing the usage of Querydsl with metaclass approach using the Querydsl annotation processor, moved devon4j specific implementation in separate guide
    * Further guides adapted regarding Quarkus:
        * REST and REST client guide
        * Bean mapping
        * Validation
        * Logging
        * Authentication and Authorization (also documented in the devonfw solutions browser)
        * Testing
        * Monitoring
        * Documented how to deal with environment specific secrets (at the moment only documented in an [issue in devon4j](https://github.com/devonfw/devon4j/issues/475)

## Reference applications

### devon4quarkus-product
https://github.com/devonfw-sample/devon4quarkus-reference
Application including a REST service for product management including also the concepts documented in the devon4j documentation:

* Abstract base class for entities
* Database connection using Postgres
* Database migration with Flyway (incl. sample data)
* Included ServicedocGen maven plugin
* Implemented test cases with Testcontainers maven plugin
* Custom ExceptionMapper to have a consitent error handling

Additionally:
* Files for Kubernetes deployment
* Files for deployment as Helm chart
    * Also documentation that show the deployment of the application with OpenTelemetry components
    * Helm chart files for the deployment of the OpenTelemetry components are located in the devonfw solution browser repository https://github.com/devonfw/solutions/tree/master/solutions/monitoring_openTelemetry

### devon4quarkus-order
https://github.com/devonfw-sample/devon4quarkus-order
Application including a REST service for order management. Connected with the devon4quarkus-product application via REST client approach (gets the products from there)

* Similar feature as the devon4quarkus-product application
* Includes REST client using `tkit-mp-restclient-plugin` with API first approach

## devonfw-ide

* Command to create a Quarkus application
