### ISSUE TITLE
Improve configuration

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#52]
The aspect configuration in devonfw can be improved:

* [x] get rid of all XML spring bean configs
* [x] remove XML spring bean configs from documentation
* [x] improve our documentation https://github.com/devonfw/devon4j/wiki/guide-configuration (and e.g. recommend and explain spring `ConfigProperties`) - done in https://github.com/devonfw/devon4j/blob/develop/documentation/guide-configuration-mapping.asciidoc

**Comment by AbhayChandel** [comment]
@hohwille Apart from feature related XML configuration files like dozer-mapping, logback etc, I am not able to recall XML based Bean configuration files. Can you point to one of the files for your first point?

**Comment by hohwille** [comment]
* https://github.com/devonfw/devon4j/blob/develop/templates/server/src/main/resources/archetype-resources/core/src/main/resources/config/app/dataaccess/NamedQueries.xml - can IMHO be deleted
* https://github.com/devonfw-wiki/devon4j/wiki/guide-batch-layer#skipping
* However, the XML spring beans config is already gone as I deleted it a longer while ago. But this might also be the reason for bug #67 
* We need to make our spring-batch approach work with spring-boot code config and update the documentation accordingly.

**Comment by hohwille** [comment]
Update:
The main aspects remaining are now related to batch and documentation.
Everything else is now solved.

**Comment by hohwille** [comment]
Issue is finally completed.
