### ISSUE TITLE
Error using JAVA 8 New Date/Time API.

### ISSUE THREAD

**Issue by jconcavi** [devonfw/devon4j#53]
We detect an error using the JAVA 8 Date/Time API and the actual DEVON implementation.

We have created an entity with LocalDate 
![image](https://user-images.githubusercontent.com/22232540/51847924-f354fb00-231c-11e9-9b8f-e4af007992ee.png)

After run the cobigen wizard this is the Interface obtained.
![image](https://user-images.githubusercontent.com/22232540/51847969-0962bb80-231d-11e9-84b5-c0fafaa87b5d.png)

Then force us to implement method, that return a LocalDate object in the Eto that actually is not supported by the default implementation of dates by OpenApi and other standards.
![image](https://user-images.githubusercontent.com/22232540/51848120-48910c80-231d-11e9-9d56-6225c44f8026.png)

Have a look to the OpenApi documentation https://swagger.io/specification/ section Data Types. More detail in https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14.

JAVA 8 Date / Time format mapper: https://dzone.com/articles/java-8-date-and-time

We can have a look into this? Is an already know way to work with this? Should this functionality been apply also in Cobigen?

**Comment by maybeec** [comment]
@jdiazgon seems to be an CobiGen only issue, could you try to reproduce it?

**Comment by jconcavi** [comment]
Hi @maybeec :

Sorry but I think that is deeper that just cobigen, the actual functionality of getBeanMapper(), is unable to handle the the LocalDate initialization.

 
![image](https://user-images.githubusercontent.com/22232540/51849170-6e1f1580-231f-11e9-9f0b-7eab287072ed.png)


That is why I create the issue to devon4j, first. Once we have this clear and tested with an example, then will be time to think how to apply into cobigen.

If you need further clarification, please ask me.

**Comment by maybeec** [comment]
Ah ok, this is a maping problem, you are right, did not get that.
Please add the required types to be mapped by reference in the dozer-mapping.xml file in your devon project like this:

```xml
copy-by-references>
      
      <copy-by-reference>java.lang.Long</copy-by-reference>
      <copy-by-reference>java.lang.Integer</copy-by-reference>
      <copy-by-reference>java.lang.Number</copy-by-reference>
      <copy-by-reference>java.util.Currency</copy-by-reference>
      <copy-by-reference>java.time.LocalTime</copy-by-reference>
      <copy-by-reference>java.time.ZonedDateTime</copy-by-reference>
      
      <!--
      <copy-by-reference>javax.money.MonetaryAmount</copy-by-reference>
      <copy-by-reference>org.javamoney.moneta.Money</copy-by-reference>
       -->
    </copy-by-references>
```

**Comment by hohwille** [comment]
BTW: We would love to go away from dozer and switch to Orika and have config as code. However, too little contributes and too much work... This dozer XML config is a painful source of trouble.

**Comment by hohwille** [comment]
For hibernate you do not need to care for JSR-310 (javax.time) anymore if you are using the version that comes with devon4j as it already includes support OOTB. That was not the case earlier.
However, from devon4j itself this is not really a bug.
We should however consider to improve the dozer config in the archetype (we can assume Java8 for every new project these days).

**Comment by jconcavi** [comment]
Hi @hohwille and @maybeec :

I test the solution on a devon4j application, and my steps done are:

Modify the dozer-mapping.xml as follows:
```xml
      <copy-by-reference>java.time.LocalDate</copy-by-reference>
      <copy-by-reference>java.time.LocalDateTime</copy-by-reference>
      <copy-by-reference>java.time.LocalTime</copy-by-reference>
      <copy-by-reference>java.time.ZonedDateTime</copy-by-reference>
      <copy-by-reference>java.time.Instant</copy-by-reference>
```

After using the cobigen tool, based on the entity:
```java
@Entity
@Table(name = "DateTimeConversion")
public class DateTimeConversionEntity extends ApplicationPersistenceEntity implements DateTimeConversion {

	private LocalDate localDate;

	private LocalTime localTime;

	private LocalDateTime localDateTime;

	private ZonedDateTime zonedDateTime;

	private Instant instant;

	private static final long serialVersionUID = 1L;
```

I modify the Eto to have all the attribute as String, and don't implements the interface:
```java
public class DateTimeConversionEto extends AbstractEto {

	private static final long serialVersionUID = 1L;

	private String localDate;

	private String localTime;

	private String localDateTime;

	private String zonedDateTime;

	private String instant;
```

So when I retry the object via rest this will be the response:
```json
{"dateTimeConversion":
    {"id":1,
     "modificationCounter":0,
     "localDate":"2019-01-29",
     "localTime":"08:31:15",
     "localDateTime":"2019-01-29T08:31:15",
     "zonedDateTime":"2019-01-29T08:31:15+01:00[Europe/Paris]",
     "instant":"2019-01-29T07:31:15Z"}
}
```

Please proceed to add the required dozer into the archetype, and if is possible document all the steps done / change cobigen to be aligned with this scenario.

**Comment by jdiazgon** [comment]
Thanks for the feedback @jconcavi. From CobiGen side, it is an easy fix. We have to create some `if` conditions to check these kind of types. If one of them is found, then we will generate `String`.

Even I think it would be possible to modify the dozer-mapping.xml by CobiGen. But I think it is a better idea to have this on the archetype, as jconcavi said.

**Comment by maybeec** [comment]
@jconcavi why do you change the Eto date time types to string already in logic layer?
For me the logical way would be to do the date time to string conversion at the service layer by jaxrs more or less automatically or by writing your own serializers/deserializers.

**Comment by jconcavi** [comment]
After a chat with @maybeec , we discuss the possibility to don't modify a lot the actual behaviour.

Create the entity with the JAVA 8 Date/Time Api, and anfter use cobigen, in the Eto, use the follwing annotations to serialize and deserialize the Date / Time classes to String or implement your own:

```java
  @JsonDeserialize(using = LocalDateDeserializer.class)
  @JsonSerialize(using = LocalDateSerializer.class)
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
  private LocalDate dateForSomething;
```

**Comment by hohwille** [comment]
https://github.com/FasterXML/jackson-modules-java8
