### ISSUE TITLE
Keycloak client authentication with angular (devon4ng)

### ISSUE THREAD

**Issue by baumeister25** [devonfw/devon4j#546]
As an architect
I want to to know how to use Keycloak for a client authentication with angular,
so that I can use it in my devon4ng project

**Comment by hohwille** [comment]
Hi @baumeister25, this is the wrong place for angular and TypeScript as this repo is `devon4j` the Java stack of devonfw.
Could you file your issue in devon4ng if you are talking about angular client?
Maybe you could directly create a PR to improve the existing docs:
https://github.com/devonfw/devon4ng/blob/f557174d98a0f87360d1c3a8bfc0f873ac5bc00b/documentation/guide-consuming-rest-services.asciidoc#store-security-token

There is nothing specific to do for keycloak. It is all about open standards which is mainly JWT or OAuth.

**Comment by baumeister25** [comment]
Hi @hohwille,
you're absolutely right. I must have overseen this when I created this issue in zenhub. 
Before I move it know, if you say there's nothing to do for this, I guess we can directly close it.
This issue was designed for the student team as a research tasks, because I was not sure if there's anything to consider.

**Comment by baumeister25** [comment]
Closing this issue as there's nothing specific for now to do with keycload in devon4ng
