### ISSUE TITLE
Analyse and compare devon4j kafka module with Spring module

### ISSUE THREAD

**Issue by baumeister25** [devonfw/devon4j#548]
This story should be seen as the starting point for the concrete tasks. 
The aim of this is to get used to Kafka, devon4j kafka module and the spring kafka module

It involves following activities:
- Setup a local kafka instance
- You can use the devon4j sample application for kafka https://github.com/devonfw-sample/devon4j-kafka-employeeapp
- Compare the devon4j kafka module with spring kafka
  - What features does devon4j offer that spring kafka does not (logging, trancing, more?)
  - Are there substitutes in spring kafka to resolve the devon4j kafka module features
  - Check with the project and devon4j product owner 

Create a short slide deck about your findings

This knowledge is essential to start removing the kafka devon4j module.

**Comment by baumeister25** [comment]
Hi @hohwille,
You're right, there's something missing here. I remember that we had a discussion and presentation in our sprint review. I was not aware that this slide deck with the analysis is missing here. I've asked @adibwaluya to add it.

In general the result was that the spring kafka implementation is a good substitute for our devon4j-kafka modul.

The next steps currently working is to adapt/implement a sample application using the spring-kafka implementation to also show this theoretical result in an executable app that considers monitoring/logging/retries/etc.

**Comment by adibwaluya** [comment]
Thanks for reminding me once again @baumeister25,
you can find the slide deck of Kafka and devone4j kafka modules below:

[Comparison Table(Kafka).pptx](https://github.com/devonfw/devon4j/files/8888502/Comparison.Table.Kafka.pptx)

Just like mentioned above, we are currently working on working on spring-kafka implementation (Logging, Tracing, Retry, etc.) on our new sample application.
