### ISSUE TITLE
Sample application should submit the status of ships via kafka

### ISSUE THREAD

**Issue by baumeister25** [devonfw/devon4j#554]
- kafka integration

- ship status can be submitted to subscribers via kafka

**Comment by hohwille** [comment]
Hi @baumeister25, thanks for your suggestion...

Which sample application are you talking about?
* https://github.com/devonfw-sample/my-thai-star
* https://github.com/devonfw-sample/devon4quarkus-reference/
* https://github.com/devonfw-sample/devon4quarkus-order/
* ...

Are you aware that there is a sample app specific for kafka:
https://github.com/devonfw-sample/devon4j-kafka-employeeapp

IMHO it would be better to submit the issue in the repository of the sample app you are talking about itself.
