### ISSUE TITLE
Validate devon4j web module

### ISSUE THREAD

**Issue by isandesh1986** [devonfw/devon4j#565]
Validate devon4j web module comparing with spring module. 

1. Check if web functionality is still relevant with latest releases of spring module.
2. If necessary, create a guide to implement a devon4j specific feature with a sample project.  In case if sample is required, the estimate can be increased to 5.(as agreed by team). 
3. Provide references to code snippets wherever possible.

Acceptance Criteria:-
1. Document the findings if required 
2. If necessary, a guide should be available to implement any devon4j specific features with a sample project. (devonfw-samples).
3. Review meeting needs to be held.

**Comment by isandesh1986** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/devon4j/565?planning-poker) with ZenHub @sujith-mn @ssarmokadam @prathibhapadma @bhargavikurella99

**Comment by sujith-mn** [comment]
https://github.com/sujith-mn/devon4j/blob/master/documentation/echo-servlet.asciidoc

https://github.com/sujith-mn/devon4j/blob/master/documentation/toggle-filter-wrapper.asciidoc
