### ISSUE TITLE
Validate devon4j rest module

### ISSUE THREAD

**Issue by isandesh1986** [devonfw/devon4j#566]
Validate devon4j rest module comparing with spring module.

1. Check if web functionality is still relevant with latest releases of spring module.
2. Create a guide to implement a devon4j specific feature with a sample project. Ex: RestExceptionFacade.
3. Provide references to code snippets wherever possible.

Acceptance Criteria:-
1. Document the findings if required 
2. A guide should be available to implement any devon4j specific features with a sample project. (devonfw-samples).
3. Review meeting needs to be held.

**Comment by ssarmokadam** [comment]
Not revevant anymore
