### ISSUE TITLE
Validate devon4j logging module

### ISSUE THREAD

**Issue by isandesh1986** [devonfw/devon4j#567]
Validate devon4j logging module comparing with log4j, sl4j, logback.

Check if web functionality is still relevant with latest releases of log4j, sl4j, logback.
Create a guide to implement a devon4j specific feature with a sample project. Ex: SecureLogging, PerformanceLogging.
Provide references to code snippets wherever possible.

**Acceptance Criteria:-**
Document the findings if required
A guide should be available to implement any devon4j specific features with a sample project. (devonfw-samples).
Review meeting needs to be held.

**Comment by isandesh1986** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/devon4j/567?planning-poker) with ZenHub @sujith-mn @ssarmokadam @prathibhapadma @bhargavikurella99

**Comment by sujith-mn** [comment]
Diaganostic Context:
https://dzone.com/articles/correlation-id-for-logging-in-microservices
DC filter
https://www.javacodegeeks.com/2014/05/implementing-correlation-ids-in-spring-boot-for-distributed-tracing-in-soamicroservices.html
Logging filter:
https://www.oracle.com/technetwork/tutorials/tutorials-1840472.html

**Comment by ssarmokadam** [comment]
Duplicate task
