### ISSUE TITLE
Consider replacing hibernate-validatior with apache BVal

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#57]
In #16 we are working on Java9+ (Java11) compatibility. The build is broken with Java11 for several reasons. One of them is that hibernate-validator depends on JavaFx. As JavaFx is no more included in Java11 it requires an external dependency. Even worse this dependency seems to be not available in maven central what broke our build. You can find the dependency here:
https://repo1.maven.org/maven2/org/hibernate/validator/hibernate-validator/6.0.14.Final/hibernate-validator-6.0.14.Final.pom
```
<profile>
  <id>jdk11+</id>
  <activation><jdk>[11,)</jdk></activation>
  <dependencies>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-base</artifactId>
      <version>${version.org.openjfx}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</profile>
```

IMHO this is an odd dependency for a validation framework. It is fine if an optional dependency on JavaFx allows to support validation also for JavaFx beans and properties. However, enforcing this dependency to all devon project does not seem right to me.

My proposal is to switch to the alternative implementation BVal: https://bval.apache.org/

**Comment by hohwille** [comment]
https://repo1.maven.org/maven2/org/apache/bval/bval-jsr/2.0.0/bval-jsr-2.0.0.pom

**Comment by AbhayChandel** [comment]
_JavaFx_ as transitive dependency for _hibernate-validator_ has  been fixed with https://github.com/hibernate/hibernate-validator/pull/978 in version _6.0.12.Final_. Hence with PR https://github.com/devonfw/devon4j/pull/63 this will be automatically fixed since Spring Boot _2.1.2.RELEASE_ has version _6.0.14.Final_ for _hibernate-validator_.

**Comment by hohwille** [comment]
Considered as completed.
