### ISSUE TITLE
Automate devon4j Release Process with Jenkins

### ISSUE THREAD

**Issue by AbhayChandel** [devonfw/devon4j#59]
It should be relatively easy to write a Jenkins Job that does
* Version Bumping (Remove -SNAPSHOT)
* Tagging
* Checkout tag
* Build and deploy to maven central
* Open next/increased -SNAPSHOT version
* Push all changes including tags to remote
* (optional and nice to have: if not triggered from develop branch, merge and push the changes to develop branch)
 
Parameters for the job would be:
* branch (default = develop)
* newVersion (default = X.Y.(Z+1)-SNAPSHOT)
 
BTW: To introduce some innovation: https://maven.apache.org/maven-ci-friendly.html
With this approach we do not even have to modify any POMs anymore for changing the version. This would make things more easy.

**Comment by hohwille** [comment]
I have no need for this anymore. @vapadwal do you know about the state of this? Can we either agree that `devonfw-ide` with `devon release` solves our issue or otherwise create this job after this issue is open for 1 year now without any update?

**Comment by vapadwal** [comment]
We do not have anything concrete on this. @AbhayChandel  had this thing on his local environment and no where it is documented or we don't have any PR for it. And as you said devon-ide solves this issue. So we can close this issue anyway

**Comment by hohwille** [comment]
Stale issue with no progress. I will close this. When someone whats to get active on this, feel free to reopen.
