### ISSUE TITLE
Bug with context-path after upgrade to spring-boot 2.0

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#6]
See https://github.com/oasp/oasp4j/issues/683

**Comment by vapadwal** [comment]
other than mention in issue #683 we have to update in below files also

https://github.com/devonfw/devon4j/blob/63b3ad7348cda89efcc784d7feb42cce8643aa11/templates/server/src/main/resources/archetype-resources/core/src/main/resources/application.properties#L9

https://github.com/devonfw/devon4j/blob/63b3ad7348cda89efcc784d7feb42cce8643aa11/templates/server/src/main/resources/archetype-resources/core/src/main/resources/config/application.properties#L9

**Comment by hohwille** [comment]
PR #17 has been merged. Hence done.
