### ISSUE TITLE
ApplicationComponentTest interferes with DiagnosticContextFilter 

### ISSUE THREAD

**Issue by maybeec** [devonfw/devon4j#60]
Inheriting ApplicationComponentTest, which sets `webEnvironment = NONE`, tests fail as of the WebConfig shipped by the archetype creates a diagnosticContextFilter, which needs to get the WebApplicationContext injected. So every test fails as there is no WebApplicationContext.

A solution would be to remove webEnvironment from the SpringBooTest annotation of ApplicationComponentTest, which would leed SpringBoot mock the WebApplicationContext by default.

**Comment by maybeec** [comment]
Regarding your question of the PR. I need to do further debugging on why it happens for me this way. I was simply thinking it might be a global issue as the diagnosticContextFilter is already quite old. Nevertheless, mabye something to be more investigated at some point in time.

**Comment by hohwille** [comment]
From #61 the question was:

> However, our tests are not failing. Is that simply because we deliver our archetype without any component test in place? I am slightly confused as we have tests for the archetype and I would like to understand what is going wrong here. Did this never work? I have done many projects with devon and written component tests derived from this class without getting issues. Is that related to #63 ?
