### ISSUE TITLE
build failure while building example project

### ISSUE THREAD

**Issue by Fadder** [devonfw/devon4j#68]
Hi everyone,

i am new to devon and i am going through your trainings.
In the training video (http://de-mucevolve02/files/videos/devon_environment/Devcon.mp4) we are creating a simple server application with devcon.
When  trying to build it (@17:50 in the video) with my freshly set up Devon-dist_3.0.0 i am getting a build failure:

>  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project exam
> pleServer-api: Compilation failure: Compilation failure:
> [ERROR] /D:/Devon-dist_3.0.0/workspaces/exampleWS/exampleServer/api/src/main/java/com/capgemini/myServer/general/service/api/
> rest/SecurityRestService.java:[9,45] package org.springframework.security.web.csrf does not exist
> [ERROR] /D:/Devon-dist_3.0.0/workspaces/exampleWS/exampleServer/api/src/main/java/com/capgemini/myServer/general/service/api/
> rest/SecurityRestService.java:[29,3] cannot find symbol
> [ERROR]   symbol:   class CsrfToken
> [ERROR]   location: interface com.capgemini.myServer.general.service.api.rest.SecurityRestService

While running with debug i found following relevant lines:

> [WARNING] The POM for com.devonfw.java.modules:devon4j-security:jar:3.0.0 is invalid, transitive dependencies (if any) will n
> ot be available: 2 problems were encountered while building the effective model for com.devonfw.java.modules:devon4j-security
> :3.0.0
> [ERROR] 'dependencies.dependency.version' for org.glassfish.jaxb:jaxb-runtime:jar is missing. @
> [ERROR] 'dependencies.dependency.version' for javax.activation:javax.activation-api:jar is missing. @ 

Can I fix this myself?

Thank you for your help & regards!
Vincent

**Comment by Fadder** [comment]
I'm feeling sorry for opening this.
I tried doing that again in the console you provide with devon via console.bat.
There it works. In command prompt it doesn't. 
I guess there is missing some software at least it is not installed globally.
Am i correct? Can you guess what is wrong?

**Comment by hohwille** [comment]
As you can see, you are using Java11:

> C:\Program Files\Java\jdk-11.0.2

However, build does not yet work with Java11. See #16 

For oasp4j-ide please read the manuals:
https://github.com/oasp/oasp4j-ide/wiki/guide-integration

**Comment by hohwille** [comment]
I will close this as invalid (resp. duplicate of #16). Feel free to convince us that there is an additional bug.
