### ISSUE TITLE
Cobigen-generated FindByCriteria behaves in unexpected way

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devon4j#69]
When using Cobigen to generate the Entity infrastructure, it produces something like:
```
public interface AccountingEntryRepository extends DefaultRepository<AccountingEntryEntity> {

  /**
   * @param criteria the {@link AccountingEntrySearchCriteriaTo} with the criteria to search.
   * @param pageRequest {@link Pageable} implementation used to set page properties like page size
   * @return the {@link Page} of the {@link AccountingEntryEntity} objects that matched the search.
   */
  default Page<AccountingEntryEntity> findByCriteria(AccountingEntrySearchCriteriaTo criteria) {
...
```
The documented parameter `pageRequest` is apparently not part of the method's signature and is not mentioned in the generated code.
Instead, the generated `AccountingEntrySearchCriteriaTo` has a member `private Pageable pageable` from `AbstractSearchCriteriaTO`.

The documentation of that is:
```
  /**
   * @return the {@link Pageable} containing the optional pagination information or {@code null}.
   */
  public Pageable getPageable() {

    return this.pageable;
  }
``` 
However, if I call `findByCriteria()` with an `AccountingEntrySearchCriteriaTo` that has its `Pageable` not set, I receiver a Null Pointer Exception (this may be due to other problems in my code, not sure yet)

I have generated my project using devcon. I use the 3.0.0 distribution with the 20190115 patch.

**Comment by jdiazgon** [comment]
Hello @Jan-PeterRichterCG,

thanks for your feedback. As this issue is related to CobiGen, I have decided to move it to our CobiGen repository. You will find it [here](https://github.com/devonfw/tools-cobigen/issues/844).
