### ISSUE TITLE
findPaginatedGeneric contains strange logic

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/devon4j#70]
Method `findPaginatedGeneric(...)` from [here](https://github.com/devonfw/devon4j/blob/develop/modules/jpa-basic/src/main/java/com/devonfw/module/jpa/dataaccess/api/QueryHelper.java#L362), contains strange logic when the `Pageable` parameter is not null.

![image](https://user-images.githubusercontent.com/31688036/54920565-d34c4d00-4f03-11e9-814c-f79ea6a0462c.png)

Even though the method seems to handle `null` Pageable objects correctly in the `if` condition, it creates a new `PageImpl` instance which `asserts` that the pageable is not null. Therefore it throws a 500 internal server error.

From @Jan-PeterRichterCG comment:

- the javadoc says: `* @param pageable contains information about the requested page and sorting.` There is no explicit documentation about a pageable that is null
- later on in the code we find ` if (pageable != null) { ...` which indicates that the code is intended to handle null-valued `pageable` parameters 
- However, if called with a null-valued `pageable`, it crashes due to `PageImp<>()` not accepting null

A clean solution would be to
- decide whether findPaginatedGeneric() shall be able to process null-valued `pageable` parameters or not
- if yes, there should be added an `else` branch to the afore mentioned ` if (pageable != null) { ...` where the local pageable is set to the default Pageable - yielding the call to `PafeImp<>()` safe.
- if no, it should be documented in the javadoc of `findPaginatedGeneric()` that the parameter `pageable` must not be null and the ` if (pageable != null) { ...` can be deleted to make the code more staight-forward.

**Comment by hohwille** [comment]
Thanks for this feedback.
IMHO this historically came from the fact that we had created our own paging solution and later switched to spring (https://github.com/oasp/oasp4j/pull/627). In our own approach the returned PaginatedList could have `null` for the paging information. With spring-data this is not allowed anymore.
As this was a "bug" in CobiGen templates and has been fixed (see devonfw/tools-cobigen#844), I will also close this issue now.
