### ISSUE TITLE
Maven version placeholders (CI-friendly-maven for devon4j)

### ISSUE THREAD

**Issue by AbhayChandel** [devonfw/devon4j#74]
This will allow to build project with different versions without need to change the pom.xml. This is a very helpful feature especially for CI/CD environment.

To read more about this Maven feature follow link below.
https://maven.apache.org/maven-ci-friendly.html

**Comment by hohwille** [comment]
I am already using this in devon-ide:
* https://github.com/devonfw/devon-ide/blob/master/.mvn/maven.config
* https://github.com/devonfw/devon-ide/blob/master/scripts/pom.xml#L14

**Comment by hohwille** [comment]
Done for devon4j itself. We did not provide it within the archetype as the maven-archetype mechanism does not fit easily with this.

**Comment by hohwille** [comment]
I have created #85 for the archetype and documentation. For `3.1.0` we close this issue and consider it feature complete.
