### ISSUE TITLE
Create environment specific properties file for configurations

### ISSUE THREAD

**Issue by AbhayChandel** [devonfw/devon4j#92]
The idea is to create environment specific files for following environments

- Development
- Test
- Production

These will be used to set environment specific configurations

**Comment by AbhayChandel** [comment]
This issue was mistakenly opened in the devon4j repository. I request the admins for this repository to kindly delete or close this issue as find you find appropriate.

**Comment by hohwille** [comment]
Now worries. Anyhow a good suggestion. We could even consider improving our configuration documentation/guide to suggest this. However, some projects want to deliver WAR with config for all environments and some other projects want to have environment config out of the software repo and keep that closer to OPS team (and keep passwords, etc. away from developers even if encrypted). So there is no generic answer, but still good to explain these options...
However, as requested, I close this issue.
